version: "3"

services:
    nodejs:
        image: lib-quality:latest
        ports:
            - "80:3000"
        env_file: .env
        depends_on:
            - db
        networks:
            - backend

    db:
        image: postgres:9.6.2-alpine
        ports:
            - "5432:5432"
        env_file: .env
        environment:
            - POSTGRES_MULTIPLE_DATABASES=test,development
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data
            - ./scripts/pg-init:/docker-entrypoint-initdb.d
        networks:
            - backend

networks:
    backend:

volumes:
    db-data:
